<?php

class COUNTRYIP{

    function getGeoDataByIp($userIp) {

        $geoData = json_decode(file_get_contents("http://ipinfo.io/{$userIp}/json"));       
        return $geoData;
        
    }
    
    
    function getCurrencySymbol($countryCode) {
        $currencies = [
            'AD' => '€',   // Andorra
            'AE' => 'د.إ',  // United Arab Emirates
            'AF' => 'AFN',  // Afghanistan
            'AG' => 'EC$',  // Antigua and Barbuda
            'AI' => '$',    // Anguilla
            'AL' => 'Lek',  // Albania
            'AM' => 'AMD',  // Armenia
            'AO' => 'Kz',   // Angola
            'AR' => '$',    // Argentina
            'AS' => '$',    // American Samoa
            'AT' => '€',    // Austria
            'AU' => '$',    // Australia
            'AW' => 'AWG',  // Aruba
            'AX' => '€',    // Åland Islands
            'AZ' => 'AZN',  // Azerbaijan
            'BA' => 'KM',   // Bosnia and Herzegovina
            'BB' => '$',    // Barbados
            'BD' => '৳',    // Bangladesh
            'BE' => '€',    // Belgium
            'BF' => 'CFA',  // Burkina Faso
            'BG' => 'лв',   // Bulgaria
            'BH' => '.د.ب', // Bahrain
            'BI' => 'BIF',  // Burundi
            'BJ' => 'CFA',  // Benin
            'BL' => '€',    // Saint Barthélemy
            'BM' => '$',    // Bermuda
            'BN' => '$',    // Brunei
            'BO' => 'Bs',   // Bolivia
            'BQ' => '$',    // Bonaire, Sint Eustatius and Saba
            'BR' => 'R$',   // Brazil
            'BS' => '$',    // Bahamas
            'BT' => 'Nu',   // Bhutan
            'BV' => 'N/A',  // Bouvet Island
            'BW' => 'P',    // Botswana
            'BY' => 'Br',   // Belarus
            'BZ' => 'BZD',  // Belize
            'CA' => '$',    // Canada
            'CC' => '$',    // Cocos (Keeling) Islands
            'CD' => 'CFA',  // Democratic Republic of the Congo
            'CF' => 'XAF',  // Central African Republic
            'CG' => 'CFA',  // Republic of the Congo
            'CH' => 'Fr.',  // Switzerland
            'CI' => 'CFA',  // Ivory Coast
            'CK' => '$',    // Cook Islands
            'CL' => '$',    // Chile
            'CM' => 'XAF',  // Cameroon
            'CN' => '¥',    // China
            'CO' => '$',    // Colombia
            'CR' => '₡',    // Costa Rica
            'CU' => '₱',    // Cuba
            'CV' => 'Esc',  // Cape Verde
            'CW' => 'ƒ',    // Curaçao
            'CX' => '$',    // Christmas Island
            'CY' => '€',    // Cyprus
            'CZ' => 'Kč',   // Czech Republic
            'DE' => '€',    // Germany
            'DJ' => 'DJF',  // Djibouti
            'DK' => 'kr',   // Denmark
            'DM' => '$',    // Dominica
            'DO' => 'RD$',  // Dominican Republic
            'DZ' => 'DZD',  // Algeria
            'EC' => '$',    // Ecuador
            'EE' => '€',    // Estonia
            'EG' => 'EGP',  // Egypt
            'EH' => 'MAD',  // Western Sahara
            'ER' => 'ERN',  // Eritrea
            'ES' => '€',    // Spain
            'ET' => 'ETB',  // Ethiopia
            'FI' => '€',    // Finland
            'FJ' => '$',    // Fiji
            'FM' => '$',    // Federated States of Micronesia
            'FO' => 'DKK',  // Faroe Islands
            'FR' => '€',    // France
            'GA' => 'CFA',  // Gabon
            'GB' => '£',    // United Kingdom
            'GD' => '$',    // Grenada
            'GE' => 'GEL',  // Georgia
            'GF' => '€',    // French Guiana
            'GG' => '£',    // Guernsey
            'GH' => 'GH₵',  // Ghana
            'GI' => '£',    // Gibraltar
            'GL' => 'DKK',  // Greenland
            'GM' => 'GMD',  // Gambia
            'GN' => 'GNF',  // Guinea
            'GP' => '€',    // Guadeloupe
            'GQ' => 'CFA',  // Equatorial Guinea
            'GR' => '€',    // Greece
            'GT' => 'GTQ',  // Guatemala
            'GU' => '$',    // Guam
            'GW' => 'CFA',  // Guinea-Bissau
            'GY' => '$',    // Guyana
            'HK' => '$',    // Hong Kong
            'HM' => 'AUD',  // Heard Island and McDonald Islands
            'HN' => 'HNL',  // Honduras
            'HR' => 'kn',   // Croatia
            'HT' => 'HTG',  // Haiti
            'HU' => 'Ft',   // Hungary
            'ID' => 'Rp',   // Indonesia
            'IE' => '€',    // Ireland
            'IL' => '₪',    // Israel
            'IM' => '£',    // Isle of Man
            'IN' => '₹',    // India
            'IO' => 'US$',  // British Indian Ocean Territory
            'IQ' => 'IQD',  // Iraq
            'IR' => 'IRR',  // Iran
            'IS' => 'kr',   // Iceland
            'IT' => '€',    // Italy
            'JE' => '£',    // Jersey
            'JM' => '$',    // Jamaica
            'JO' => 'JOD',  // Jordan
            'JP' => '¥',    // Japan
            'KE' => 'KES',  // Kenya
            'KG' => 'KGS',  // Kyrgyzstan
            'KH' => 'KHR',  // Cambodia
            'KI' => 'A$',   // Kiribati
            'KM' => 'KMF',  // Comoros
            'KN' => '$',    // Saint Kitts and Nevis
            'KP' => '₩',    // North Korea
            'KR' => '₩',    // South Korea
            'KW' => 'KWD',  // Kuwait
            'KY' => '$',    // Cayman Islands
            'KZ' => '₸',    // Kazakhstan
            'LA' => 'LAK',  // Laos
            'LB' => 'LBP',  // Lebanon
            'LC' => '$',    // Saint Lucia
            'LI' => 'CHF',  // Liechtenstein
            'LK' => 'Rs',   // Sri Lanka
            'LR' => 'LRD',  // Liberia
            'LS' => 'LSL',  // Lesotho
            'LT' => '€',    // Lithuania
            'LU' => '€',    // Luxembourg
            'LV' => '€',    // Latvia
            'LY' => 'LYD',  // Libya
            'MA' => 'MAD',  // Morocco
            'MC' => '€',    // Monaco
            'MD' => 'MDL',  // Moldova
            'ME' => '€',    // Montenegro
            'MF' => '€',    // Saint Martin
            'MG' => 'MGA',  // Madagascar
            'MH' => '$',    // Marshall Islands
            'MK' => 'MKD',  // North Macedonia
            'ML' => 'CFA',  // Mali
            'MM' => 'MMK',  // Myanmar
            'MN' => '₮',    // Mongolia
            'MO' => 'MOP',  // Macau
            'MP' => '$',    // Northern Mariana Islands
            'MQ' => '€',    // Martinique
            'MR' => 'MRO',  // Mauritania
            'MS' => '$',    // Montserrat
            'MT' => '€',    // Malta
            'MU' => '₨',    // Mauritius
            'MV' => 'Rf',   // Maldives
            'MW' => 'MWK',  // Malawi
            'MX' => '$',    // Mexico
            'MY' => 'RM',   // Malaysia
            'MZ' => 'MZN',  // Mozambique
            'NA' => 'NAD',  // Namibia
            'NC' => '₣',    // New Caledonia
            'NE' => 'CFA',  // Niger
            'NF' => '$',    // Norfolk Island
            'NG' => '₦',    // Nigeria
            'NI' => 'C$',   // Nicaragua
            'NL' => '€',    // Netherlands
            'NO' => 'kr',   // Norway
            'NP' => '₨',    // Nepal
            'NR' => '$',    // Nauru
            'NU' => 'NZ$',  // Niue
            'NZ' => 'NZ$',  // New Zealand
            'OM' => '﷼',   // Oman
            'PA' => 'B/.',  // Panama
            'PE' => 'S/',   // Peru
            'PF' => 'CFP',  // French Polynesia
            'PG' => 'PGK',  // Papua New Guinea
            'PH' => '₱',    // Philippines
            'PK' => 'Rs',   // Pakistan
            'PL' => 'zł',   // Poland
            'PM' => '€',    // Saint Pierre and Miquelon
            'PN' => '$',    // Pitcairn Islands
            'PR' => '$',    // Puerto Rico
            'PT' => '€',    // Portugal
            'PW' => '$',    // Palau
            'PY' => '₲',    // Paraguay
            'QA' => 'QR',   // Qatar
            'RE' => '€',    // Réunion
            'RO' => 'RON',  // Romania
            'RS' => 'RSD',  // Serbia
            'RU' => '₽',    // Russia
            'RW' => 'RWF',  // Rwanda
            'SA' => 'ر.س',  // Saudi Arabia
            'SB' => '$',    // Solomon Islands
            'SC' => '₨',    // Seychelles
            'SD' => 'SDG',  // Sudan
            'SE' => 'kr',   // Sweden
            'SG' => 'S$',   // Singapore
            'SH' => '£',    // Saint Helena
            'SI' => '€',    // Slovenia
            'SJ' => 'NOK',  // Svalbard and Jan Mayen
            'SK' => '€',    // Slovakia
            'SL' => 'SLL',  // Sierra Leone
            'SM' => '€',    // San Marino
            'SN' => 'CFA',  // Senegal
            'SO' => 'SOS',  // Somalia
            'SR' => 'SRD',  // Suriname
            'SS' => 'SSP',  // South Sudan
            'ST' => 'STN',  // São Tomé and Príncipe
            'SV' => '$',    // El Salvador
            'SX' => 'ƒ',    // Sint Maarten
            'SY' => 'SYP',  // Syria
            'SZ' => 'SZL',  // Eswatini
            'TC' => '$',    // Turks and Caicos Islands
            'TD' => 'CFA',  // Chad
            'TF' => '€',    // French Southern and Antarctic Lands
            'TG' => 'CFA',  // Togo
            'TH' => '฿',    // Thailand
            'TJ' => 'TJS',  // Tajikistan
            'TK' => '$',    // Tokelau
            'TL' => 'US$',  // East Timor
            'TM' => 'TMT',  // Turkmenistan
            'TN' => 'TND',  // Tunisia
            'TO' => 'TOP',  // Tonga
            'TR' => '₺',    // Turkey
            'TT' => '$',    // Trinidad and Tobago
            'TV' => '$',    // Tuvalu
            'TZ' => 'TSh',  // Tanzania
            'UA' => '₴',    // Ukraine
            'UG' => 'UGX',  // Uganda
            'UM' => '$',    // United States Minor Outlying Islands
            'US' => '$',    // United States
            'UY' => '$U',   // Uruguay
            'UZ' => 'UZS',  // Uzbekistan
            'VA' => '€',    // Vatican City
            'VC' => '$',    // Saint Vincent and the Grenadines
            'VE' => 'Bs.S.',// Venezuela
            'VG' => '$',    // British Virgin Islands
            'VI' => '$',    // United States Virgin Islands
            'VN' => '₫',    // Vietnam
            'VU' => 'VUV',  // Vanuatu
            'WF' => 'CFP',  // Wallis and Futuna
            'WS' => 'WS$',  // Samoa
            'YE' => '﷼',   // Yemen
            'YT' => '€',    // Mayotte
            'ZA' => 'R',    // South Africa
            'ZM' => 'ZK',   // Zambia
            'ZW' => 'Z$',   // Zimbabwe
        ];
    
        return $currencies[$countryCode] ?? '₹'; 
    }

}


?>